services:
  whmcs:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
        WHMCS_VERSION: ${WHMCS_VERSION:-8.11.2}
        ADMIN_URI: ${ADMIN_URI:-admin}
        ENVIRONMENT: ${ENVIRONMENT:-development}
    container_name: "${CONTAINER_NAME:-whmcs}"
    env_file:
      - ./.env
    ports:
      - "${HOST_PORT:-20080}:80"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-whmcs}
      - DB_USER=${DB_USER:-whmcs}
      - DB_PASSWORD=${DB_PASSWORD:-whmcs_password}
      - WHMCS_VERSION=${WHMCS_VERSION:-8.11.2}
      - DEVELOPMENT_MODE=true
      - ENVIRONMENT=development
      - WHMCS_DOMAIN=dominios.local
    networks:
      whmcs_network:
        ipv4_address: 172.18.18.4
    volumes:
      # Development: Direct mount for real-time editing with macOS optimization
      - ./app:/var/www/html:delegated
      - ./scripts:/scripts:ro,delegated
      - ./settings.json:/var/www/html/../settings.json:ro,delegated
      # Use named volume for vendor directory to avoid file system conflicts
      - vendor_data:/var/www/html/vendor
      # Mount healthcheck.php separately to avoid deadlock issues
      - ./config/docker/healthcheck.php:/var/www/html/healthcheck.php
      # Add additional named volumes for problematic directories
      - templates_c_data:/var/www/html/templates_c
      - attachments_data:/var/www/html/attachments
    depends_on:
      - db
      - mailpit
    restart: unless-stopped
    # Debug healthcheck - simplified to identify issue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  db:
    image: percona/percona-server:8.0
    container_name: "${CONTAINER_NAME:-whmcs}_db"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${DB_NAME:-whmcs}
      - MYSQL_USER=${DB_USER:-whmcs}
      - MYSQL_PASSWORD=${DB_PASSWORD:-whmcs_password}
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    restart: unless-stopped
    ports:
      - "${DB_PORT:-23306}:3306"
    networks:
      whmcs_network:
        ipv4_address: 172.18.18.5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  mailpit:
    image: axllent/mailpit:latest
    container_name: "${CONTAINER_NAME:-whmcs}_mailpit"
    ports:
      - "${MAILPIT_HTTP_PORT:-21025}:8025"  # Web UI
      - "${MAILPIT_SMTP_PORT:-21587}:1025"  # SMTP server
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
      - MP_UI_AUTH_FILE=
      - MP_MAX_MESSAGES=5000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_REQUIRE_TLS=false
    volumes:
      - mailpit_data:/data
    restart: unless-stopped
    networks:
      whmcs_network:
        ipv4_address: 172.18.18.6
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/api/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${CONTAINER_NAME:-whmcs}_phpmyadmin"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER:-whmcs}
      - PMA_PASSWORD=${DB_PASSWORD:-whmcs_password}
      - UPLOAD_LIMIT=100M
    ports:
      - "${PHPMYADMIN_PORT:-38765}:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      whmcs_network:
        ipv4_address: 172.18.18.7

networks:
  whmcs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.18.0/24
          gateway: 172.18.18.1

volumes:
  db_data:
  vendor_data:
  templates_c_data:
  attachments_data:
  mailpit_data:
